-- MySQL Script generated by MySQL Workbench
-- 04/14/18 13:59:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vigilancia_tecnologica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vigilancia_tecnologica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vigilancia_tecnologica` DEFAULT CHARACTER SET utf8 ;
USE `vigilancia_tecnologica` ;

-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Datos_Personales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Datos_Personales` (
  `idDatos_Personales` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `app` VARCHAR(200) NULL DEFAULT NULL,
  `apm` VARCHAR(200) NULL DEFAULT NULL,
  `sexo` VARCHAR(200) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `puesto` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idDatos_Personales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Procesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Procesos` (
  `idProcesos` INT NOT NULL AUTO_INCREMENT,
  `nombre_proceso` VARCHAR(200) NULL,
  `descripcion` TEXT NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`idProcesos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(200) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `estatus` TINYINT(1) NULL DEFAULT NULL,
  `tipo_user` INT NULL DEFAULT NULL,
  `Datos_Personales_idDatos_Personales` INT NOT NULL,
  `Procesos_idProcesos` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`, `Datos_Personales_idDatos_Personales`, `Procesos_idProcesos`),
  INDEX `fk_Usuarios_Datos_Personales1_idx` (`Datos_Personales_idDatos_Personales` ASC),
  INDEX `fk_Usuarios_Procesos1_idx` (`Procesos_idProcesos` ASC),
  CONSTRAINT `fk_Usuarios_Datos_Personales1`
    FOREIGN KEY (`Datos_Personales_idDatos_Personales`)
    REFERENCES `vigilancia_tecnologica`.`Datos_Personales` (`idDatos_Personales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Procesos1`
    FOREIGN KEY (`Procesos_idProcesos`)
    REFERENCES `vigilancia_tecnologica`.`Procesos` (`idProcesos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Intereses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Intereses` (
  `idIntereses` INT NOT NULL AUTO_INCREMENT,
  `nombre_interes` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `estatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idIntereses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Noticias` (
  `idNoticias` INT NOT NULL AUTO_INCREMENT,
  `nombre_noticia` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `enlace` TEXT NULL DEFAULT NULL,
  `estatus` TINYINT(1) NULL DEFAULT NULL,
  `Intereses_idIntereses` INT NOT NULL,
  PRIMARY KEY (`idNoticias`, `Intereses_idIntereses`),
  INDEX `fk_Noticias_Intereses1_idx` (`Intereses_idIntereses` ASC),
  CONSTRAINT `fk_Noticias_Intereses1`
    FOREIGN KEY (`Intereses_idIntereses`)
    REFERENCES `vigilancia_tecnologica`.`Intereses` (`idIntereses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Compartir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Compartir` (
  `idCompartir` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Compartircon` INT NULL DEFAULT NULL,
  `estatus` TINYINT(1) NULL DEFAULT NULL,
  `Noticias_idNoticias` INT NOT NULL,
  `Noticias_Intereses_idIntereses` INT NOT NULL,
  PRIMARY KEY (`idCompartir`, `Usuarios_idUsuarios`, `Noticias_idNoticias`, `Noticias_Intereses_idIntereses`),
  INDEX `fk_Compartir_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_Compartir_Noticias1_idx` (`Noticias_idNoticias` ASC, `Noticias_Intereses_idIntereses` ASC),
  CONSTRAINT `fk_Compartir_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vigilancia_tecnologica`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compartir_Noticias1`
    FOREIGN KEY (`Noticias_idNoticias` , `Noticias_Intereses_idIntereses`)
    REFERENCES `vigilancia_tecnologica`.`Noticias` (`idNoticias` , `Intereses_idIntereses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Relacion_Intereses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Relacion_Intereses` (
  `idRelacion_Intereses` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Intereses_idIntereses` INT NOT NULL,
  PRIMARY KEY (`idRelacion_Intereses`, `Usuarios_idUsuarios`, `Intereses_idIntereses`),
  INDEX `fk_Relacion_Intereses_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_Relacion_Intereses_Intereses1_idx` (`Intereses_idIntereses` ASC),
  CONSTRAINT `fk_Relacion_Intereses_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vigilancia_tecnologica`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relacion_Intereses_Intereses1`
    FOREIGN KEY (`Intereses_idIntereses`)
    REFERENCES `vigilancia_tecnologica`.`Intereses` (`idIntereses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Califica_Noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Califica_Noticia` (
  `idCalifica_Noticia` INT NOT NULL AUTO_INCREMENT,
  `calificacion` INT NULL DEFAULT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Noticias_idNoticias` INT NOT NULL,
  PRIMARY KEY (`idCalifica_Noticia`, `Usuarios_idUsuarios`, `Noticias_idNoticias`),
  INDEX `fk_Califica_Noticia_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_Califica_Noticia_Noticias1_idx` (`Noticias_idNoticias` ASC),
  CONSTRAINT `fk_Califica_Noticia_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vigilancia_tecnologica`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Califica_Noticia_Noticias1`
    FOREIGN KEY (`Noticias_idNoticias`)
    REFERENCES `vigilancia_tecnologica`.`Noticias` (`idNoticias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Interes_Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Interes_Proceso` (
  `idInteres_Proceso` INT NOT NULL AUTO_INCREMENT,
  `Intereses_idIntereses` INT NOT NULL,
  `Procesos_idProcesos` INT NOT NULL,
  PRIMARY KEY (`idInteres_Proceso`, `Intereses_idIntereses`, `Procesos_idProcesos`),
  INDEX `fk_Interes_Proceso_Intereses1_idx` (`Intereses_idIntereses` ASC),
  INDEX `fk_Interes_Proceso_Procesos1_idx` (`Procesos_idProcesos` ASC),
  CONSTRAINT `fk_Interes_Proceso_Intereses1`
    FOREIGN KEY (`Intereses_idIntereses`)
    REFERENCES `vigilancia_tecnologica`.`Intereses` (`idIntereses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Interes_Proceso_Procesos1`
    FOREIGN KEY (`Procesos_idProcesos`)
    REFERENCES `vigilancia_tecnologica`.`Procesos` (`idProcesos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vigilancia_tecnologica`.`Avisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`Avisos` (
  `idAvisos` INT NOT NULL AUTO_INCREMENT,
  `nombre_aviso` VARCHAR(100) NULL,
  `ruta_imagen` VARCHAR(100) NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idAvisos`, `Usuarios_idUsuarios`),
  INDEX `fk_Avisos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  CONSTRAINT `fk_Avisos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `vigilancia_tecnologica`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vigilancia_tecnologica` ;

-- -----------------------------------------------------
-- Placeholder table for view `vigilancia_tecnologica`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vigilancia_tecnologica`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `vigilancia_tecnologica`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vigilancia_tecnologica`.`view1`;
USE `vigilancia_tecnologica`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
